City-of-Helsinki/infraohjelmointi-ui

- src/components/AuthGuard/AuthGuard.test.tsx
- src/components/AuthGuard/AuthGuard.tsx
- src/components/Loader/Loader.test.tsx
- src/components/Notification/Notification.test.tsx
- src/components/Project/ProjectBasics/ProjectBasicsForm.test.tsx
- src/components/Project/ProjectBasics/ProjectSidePanel.tsx
- src/components/Project/ProjectBasics/styles.css
- src/components/Project/ProjectToolbar/ProjectToolbar.test.tsx
- src/components/Sidebar/SideBar.test.tsx
- src/components/TopBar/TopBar.test.tsx
- src/components/shared/SelectField.tsx
- src/hooks/useOptions.ts
- src/hooks/useProjectBasicsForm.ts
- src/i18n/fi.json
- src/interfaces/common.ts
- src/interfaces/projectInterfaces.ts
- src/interfaces/userInterfaces.ts
- src/mocks/mockLists.ts
- src/mocks/mockPersons.ts
- src/mocks/mockProject.ts
- src/mocks/mockUser.ts
- src/mocks/mockUsers.ts
- src/reducers/authSlice.ts
- src/reducers/listsSlice.ts
- src/services/personServices.ts
- src/views/ErrorView/ErrorView.test.tsx
- src/views/ProjectView/ProjectView.test.tsx
- src/views/ProjectView/ProjectView.tsx
- New ResponsiblePersons for project card form
- New ResponsiblePersons slice to listSlice
- Tests for new persons list and getResponsiblePersonsThunk()
- Rename of getUsersThunk to get UserThunk
- Rename of IUser to IPerson
> Story/io 194/project card responsible persons

- package.json
- src/App.test.tsx
- src/App.tsx
- src/components/Project/ProjectHashTags/styles.css
- src/index.tsx
- yarn.lock
- udpated react-router and react-router-dom
- started using <Router /> instead of createBrowserRouter
> Improvement/io 259/route improvements

- src/components/Planning/PlanningClassesTable/styles.css
- src/components/Planning/PlanningGroupsTable/PlanningGroupsTableRow.tsx
- src/components/Planning/PlanningGroupsTable/styles.css
- src/components/Planning/PlanningInfoPanel/styles.css
- src/components/Planning/PlanningYearsTable/styles.css
- src/components/shared/CustomTag.tsx
- Added category tag to planning table project header 
- Removed icons not to be used in MVP
> Story/io 156/show category in planning list view

- src/components/Project/ProjectBasics/ProjectBasics.tsx
- src/components/Project/ProjectBasics/styles.css
- src/reducers/projectSlice.ts
- Hide sidebar if project isn't selected, 
- Reset selected project before a new project is selected (this will cause TextAreaFields for project basics form to re-calculate their height)
> story/io-257/ project-card-description-field-change

- src/components/Planning/PlanningInfoPanel/PlanningInfoPanel.tsx
- src/components/Planning/PlanningInfoPanel/styles.css
- src/i18n/fi.json
- src/views/ProjectView/ProjectView.test.tsx
- Changes to planning info panel for planning list view
> Story/io 264/plan list show current view

- src/components/Planning/PlanningInfoPanel/PlanningInfoPanel.tsx
- src/components/Planning/PlanningTable/PlanningRow/PlanningRow.tsx
- src/components/Planning/PlanningTable/PlanningRow/ProjectRow/ProjectRow.tsx
- src/components/Planning/PlanningTable/PlanningRow/ProjectRow/styles.css
- src/components/Search/FreeSearchForm.tsx
- src/components/Search/Search.test.tsx
- src/components/Search/styles.css
- src/components/SearchResults/SearchResultsCard.tsx
- src/components/SearchResults/SearchTerms.tsx
- src/hooks/usePlanningRows.ts
- src/hooks/useSearchResultsList.ts
- src/interfaces/searchInterfaces.ts
- src/mocks/mockSearch.ts
- src/services/projectServices.ts
- src/utils/interceptors.ts
- src/views/SearchResultsView/SearchResultsView.test.tsx
- Navigate to project from search results view
- Focus the project and highlight it when navigated
- New "?project" search params for planning view
> Story/io 290/navigate to project from search results

- src/components/Planning/PlanningTable/PlanningRow/PlanningRow.tsx
- src/components/Planning/PlanningToolbar/PlanningToolbar.tsx
- src/components/Planning/ProjectProgrammedDialog/ProjectProgrammedDialog.test.tsx
- src/components/Planning/ProjectProgrammedDialog/ProjectProgrammedDialog.tsx
- src/components/Planning/ProjectProgrammedDialog/ProjectProgrammedSearch.tsx
- src/components/Planning/ProjectProgrammedDialog/SelectedProjectCard.tsx
- src/components/Planning/ProjectProgrammedDialog/index.tsx
- src/components/Planning/ProjectProgrammedDialog/styles.css
- src/components/Project/ProjectBasics/ProjectBasicsForm.test.tsx
- src/hooks/usePlanningRows.ts
- src/i18n/fi.json
- src/interfaces/projectInterfaces.ts
- src/interfaces/searchInterfaces.ts
- src/services/projectServices.ts
- src/utils/mockGetResponseProvider.ts
- src/views/PlanningView/PlanningView.tsx
- Dialog made for searching for and adding projects  to planning list view
- After addition, the project phase is changed to programming
- To be able to open the dialog, the user needs to be under any class or subclass balk in the planning view
- After adding a non-programmed project to planning view, the lists of project under the balk you are on updates
> Story/io 260/proposed project to planning list

- src/components/Planning/ProjectProgrammedDialog/ProjectProgrammedDialog.tsx
- src/components/Planning/ProjectProgrammedDialog/ProjectProgrammedSearch.tsx
Renamed onProjectClick callback to onProjectsSelect
Function now takes in an array instead of a value 
removed unused for loop
Fixed duplicates in search suggestions
> onSubmit function refactor to accept a list

- .eslintrc.json
- src/App.tsx
- src/components/CustomContextMenu/ContextMenus/NewItemMenu/NewItemMenu.tsx
- src/components/Planning/PlanningToolbar/PlanningToolbar.tsx
- src/components/Project/ProjectBasics/ProjectBasics.tsx
- src/components/Project/ProjectBasics/ProjectForm/ProjectForm.test.tsx
- src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx
- src/components/Project/ProjectBasics/ProjectForm/ProjectFormBanner.tsx
- src/components/Project/ProjectBasics/ProjectForm/ProjectInfoSection.tsx
- src/components/Project/ProjectBasics/ProjectForm/ProjectStatusSection.tsx
- src/components/Project/ProjectHeader/ProjectFavouriteField.tsx
- src/components/Project/ProjectHeader/ProjectHeader.test.tsx
- src/components/Project/ProjectHeader/ProjectHeader.tsx
- src/components/Project/ProjectHeader/ProjectNameFields.tsx
- src/components/Project/ProjectNotes/ProjectNotes.test.tsx
- src/components/shared/IconButton.tsx
- src/forms/useProjectForm.ts
- src/i18n/fi.json
- src/interfaces/eventInterfaces.ts
- src/interfaces/formInterfaces.ts
- src/interfaces/projectInterfaces.ts
- src/reducers/projectSlice.ts
- src/services/projectServices.ts
- src/views/ProjectView/ProjectView.test.tsx
- src/views/ProjectView/ProjectView.tsx
- Reusing existing project form to create new projects
- Made a new redux state for mode on project slice
- Wrote test for new project creation
> Story/io 312/create new project

- src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx
- src/components/Project/ProjectHeader/ProjectHeader.tsx
- src/utils/common.ts
- Added logic to move finances correctly when changing dates in project card
> io-299/ Finance update when changing dates in project card

- src/App.test.tsx
- src/App.tsx
- src/components/Planning/PlanningTable/PlanningRow/PlanningCell.tsx
- src/components/Planning/PlanningTable/PlanningRow/PlanningForecastSums.tsx
- src/components/Planning/PlanningTable/PlanningRow/PlanningHead.tsx
- src/components/Planning/PlanningTable/PlanningRow/PlanningRow.tsx
- src/components/Planning/PlanningTable/PlanningRow/styles.css
- src/hooks/useCoordinationRows.ts
- src/hooks/useNumberInput.ts
- src/hooks/useOnClickOutsideRef.ts
- src/hooks/usePlanningRows.ts
- src/hooks/useSummaryRows.ts
- src/i18n/fi.json
- src/interfaces/classInterfaces.ts
- src/interfaces/eventInterfaces.ts
- src/interfaces/planningInterfaces.ts
- src/mocks/mockClassFinances.ts
- src/reducers/classSlice.ts
- src/reducers/locationSlice.ts
- src/reducers/planningSlice.ts
- src/services/classService.ts
- src/utils/calculations.ts
- src/utils/planningRowUtils.ts
- src/views/PlanningView/PlanningView.test.tsx
- patch finances (frameBudget and budgetChange) in coordination view
- made useCoordinationRows more readable
> Story/io 332/coordination finances

- src/components/Planning/PlanningTable/PlanningRow/ProjectRow/ProjectCell.tsx
- src/components/Planning/PlanningTable/PlanningRow/ProjectRow/ProjectHead.tsx
- src/i18n/fi.json
- src/utils/interceptors.ts
- adds error notifications for changing project phase and budget to the planning and coordination view
> Story/io 346/planning view project error handling

- src/App.tsx
- src/components/AuthGuard/AuthGuard.tsx
- src/components/Planning/GroupDialog/GroupDialog.test.tsx
- src/components/Planning/GroupDialog/GroupProjectSearch.tsx
- src/components/Planning/PlanningTable/PlanningRow/PlanningCell.tsx
- src/components/Planning/PlanningTable/PlanningRow/PlanningForecastSums.tsx
- src/components/Planning/PlanningTable/PlanningRow/ProjectRow/ProjectCell.tsx
- src/components/Planning/PlanningTable/PlanningRow/ProjectRow/projectCellUtils.ts
- src/hooks/useCoordinationRows.ts
- src/hooks/useFinanceUpdates.ts
- src/hooks/usePlanningRows.ts
- src/hooks/useProjectRow.ts
- src/interfaces/eventInterfaces.ts
- src/interfaces/planningInterfaces.ts
- src/interfaces/projectInterfaces.ts
- src/interfaces/searchInterfaces.ts
- src/mocks/mockProject.ts
- src/reducers/classSlice.ts
- src/reducers/locationSlice.ts
- src/services/classServices.ts
- src/services/locationServices.ts
- src/services/projectServices.ts
- src/utils/calculations.ts
- src/utils/mockGetResponseProvider.ts
- src/utils/planningRowUtils.ts
- src/views/PlanningView/PlanningView.test.tsx
- Additional coordination finance levels (locations)
- Forced to frame view finances
- Add TA-muutos to frame budget
- Redirect the authenticated user back to the initially opened page after authentication
- Remove TA-muutos from groups and planning view
> Story/io 368/forced to frame view finances

- src/components/Planning/PlanningTable/PlanningRow/ProjectRow/ProjectHead.tsx
- src/components/Planning/PlanningToolbar/PlanningToolbar.tsx
- src/components/Planning/PlanningToolbar/styles.css
- src/components/Planning/ProjectProgrammedDialog/ProjectProgrammedDialog.test.tsx
- src/components/Project/ProjectHeader/ProjectHeader.test.tsx
- src/components/Project/ProjectHeader/ProjectHeader.tsx
- src/mocks/mockProject.ts
- src/reducers/authSlice.ts
- src/views/PlanningView/PlanningView.test.tsx
- src/views/SearchResultsView/SearchResultsView.test.tsx
- show group name in project form
> story/io 375/project group info to project form

- src/App.test.tsx
- src/App.tsx
- src/components/Planning/GroupDialog/GroupDialog.test.tsx
- src/components/Planning/GroupDialog/GroupDialog.tsx
- src/components/Planning/PlanningTable/PlanningRow/ProjectRow/projectCellUtils.ts
- src/components/Planning/ProjectProgrammedDialog/ProjectProgrammedDialog.test.tsx
- src/components/Project/ProjectHeader/ProjectHeader.test.tsx
- src/components/Project/ProjectHeader/ProjectHeader.tsx
- src/forms/useGroupForm.ts
- src/hooks/useCoordinationRows.ts
- src/hooks/useFinanceUpdates.ts
- src/hooks/usePlanningRows.ts
- src/interfaces/eventInterfaces.ts
- src/reducers/groupSlice.ts
- src/services/groupServices.ts
- src/utils/mockGetResponseProvider.ts
- src/utils/planningRowUtils.ts
- src/views/PlanningView/CoordinationView.test.tsx
- src/views/PlanningView/PlanningView.test.tsx
- Added groups in coordination view
- Created new thunks for coordination  groups
- Modified group state in redux
> Story/io 367/adding groups to coordination

- src/App.tsx
- src/components/AuthGuard/AuthGuard.tsx
- src/utils/interceptors.ts
Fix problem with error notification which pops up when user not logged in
> Cancel requests if no user exists in axios interceptors

- src/components/Planning/PlanningTable/PlanningRow/PlanningForecastSums.tsx
- src/hooks/useNumberInput.ts
Reverts City-of-Helsinki/infraohjelmointi-ui#96
> Revert "Story/io 373/enable negative values ta muutos"

- src/components/Planning/PlanningTable/PlanningRow/PlanningCell.tsx
- src/components/Planning/PlanningTable/PlanningRow/PlanningForecastSums.tsx
- src/hooks/useNumberInput.ts
- show correct number on input value when it is opened
- don't allow to make request with negative numbers
> Story/io 384/enable negative values ta muutos

- src/components/Admin/AdminHashtags/AddHashtagDialog.tsx
- src/components/Planning/PlanningTable/PlanningRow/PlanningForecastSums.tsx
- src/i18n/fi.json
- added an error notification for when TA muutos would make the frame budget to be negative
- Ticket: [https://helsinkisolutionoffice.atlassian.net/browse/IO-384](https://helsinkisolutionoffice.atlassian.net/browse/IO-384)
> add an error message when frame budget would be negative

- src/components/Planning/PlanningTable/PlanningRow/PlanningForecastSums.tsx
- Update calc to check that frame budget value is not negative
- Send number and not string to backend
> update calc and send int value to backend

- src/components/Project/ProjectNotes/ProjectNote.tsx
- src/components/Project/ProjectNotes/ProjectNoteHistoryRow.tsx
- src/components/Project/ProjectNotes/ProjectNotes.test.tsx
- src/interfaces/noteInterfaces.ts
- src/mocks/mockNotes.ts
- Note author was "undefined undefined" before. Now it should be fixed with new notes. Some old notes might still have "undefined undefined" cause they either didn't have an author when read from excels or the author info didn't come from PW
- Ticket: [https://futurice.atlassian.net/browse/HKISD-4](https://futurice.atlassian.net/browse/HKISD-4)
> Fix: author of a note

- README.md
Added instructions for how to do a production release.
> docs: add production release guide

- src/components/Planning/PlanningTable/PlanningRow/PlanningRow.tsx
There were two similar tickets:
https://futurice.atlassian.net/browse/HKISD-12
https://futurice.atlassian.net/browse/HKISD-26
This fix solves the problem with the framebudgets now but later when we have time, we should check the possible problem with the projectGroup/projectClass thing that I commented to the code
> HKISD-12 / HKISD-26: Problem with the framebudgets

- src/hooks/usePlanningRows.ts
- src/utils/common.ts
- src/utils/planningRowUtils.ts
- Users were not able to save projects under classes that don't have subClasses
> Fix projects didn't save under classes that don't have subClasses

- src/components/AuthGuard/AuthGuard.tsx
- navigating to new project card got broken here: https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/129
- it redirected the user to 404 when trying to create a new project
- this PR fixes the issue
> fix navigating to new project card

- src/components/Project/ProjectBasics/ProjectForm/ErrorSummary.tsx
- src/components/Project/ProjectBasics/ProjectForm/ProjectStatusSection.tsx
- Rename component name from "ErroSummary" to "Erro_r_Summary"
- Make district option optional on project card view
> KHISD-51: ProjectForm optional district

- src/forms/useProjectForm.ts
[HKISD-27 ](https://futurice.atlassian.net/browse/HKISD-27)
Loading the project from the link would not populate the financial section with correct project data.
The problem was related to classes, subclasses and masterClass arrays not being populated beforehand.  
Add dependency to useProjectForm hook to update formValues on classes, subClasses, masterClasses, districts, divisions, subDivisions updates.
> HKISD-27: fix project financial section data

- src/components/Report/DownloadPdfButton.tsx
- src/components/Report/ReportRow.tsx
Reverts City-of-Helsinki/infraohjelmointi-ui#171
> Revert "Remove projects fetch from reports for testing purposes in dev environment"

- src/components/Report/PdfReports/TableRow.tsx
- src/utils/reportHelpers.ts
The client wanted to have indentations on the report and also hide those TA parts that don't have any planned budgets.
> IO-336: added small changes

- src/components/Report/PdfReports/TableRow.tsx
- src/utils/calculations.ts
- src/utils/reportHelpers.ts
The numbers were converted into millions and rounded differently earlier and I fixed that in order to show the numbers in a right format
> IO-338: change report's number calculations

- src/components/Report/PdfReports/TableRow.tsx
- src/i18n/fi.json
- src/interfaces/reportInterfaces.ts
- src/utils/reportHelpers.ts
The client wanted that `TAE&TSE raami` is changed to `TA, käytettävissä oleva määräraha` and `Ylityspaine` to `Muutospaine`
> IO-336: text changes

- src/components/Report/DownloadCsvButton.tsx
- src/components/Report/DownloadPdfButton.tsx
- src/components/Report/PdfReports/ReportTable.tsx
- src/components/Report/ReportRow.tsx
- src/hooks/usePlanningRows.ts
- src/interfaces/reportInterfaces.ts
- src/utils/reportHelpers.ts
- fixed an issue where projects and groups were not showing in the construction report if they were under divisions
- fixed an issue with project locations not showing on the report
> IO-334/fixes for construction report

- src/components/Report/DownloadCsvButton.tsx
- src/components/Report/DownloadPdfButton.tsx
- src/components/Report/ReportRow.tsx
https://futurice.atlassian.net/browse/HKISD-111
> HKISD-111: Changed the report to show coordination view data

- src/utils/reportHelpers.ts
- fix years in the title of operational analysis report
> Fix: years in the title of operational analysis report

- src/components/Report/DownloadCsvButton.tsx
- src/components/Report/DownloadPdfButton.tsx
- src/components/Report/ReportRow.tsx
- src/interfaces/reportInterfaces.ts
- src/services/listServices.ts
- src/utils/reportHelpers.ts
- src/views/ReportsView/ReportsView.tsx
- all the data is now fetched from the backend so issue with the store don't cause issues with the reports
- can be tested by downloading operational environment analysis report and/or construction report
> HKISD-85/fix loading reports when navigating to reportsView

- src/components/Report/DownloadCsvButton.tsx
- src/components/Report/DownloadPdfButton.tsx
- src/components/Report/PdfReports/DocumentHeader.tsx
- src/components/Report/ReportRow.tsx
- src/interfaces/reportInterfaces.ts
- src/services/listServices.ts
- src/utils/reportHelpers.ts
- src/views/ReportsView/ReportsView.tsx
- fixed loading report data when navigating directly to reportsView
> Fix: loading report data when navigating directly to reportsView

- src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx
- fixes: [https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-87](https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-87)
- changing two dates from the project form didn't move budgets, but left budgets outside the schedule of the project
> fix: moving budgets when changing two dates from the project form

- src/components/Project/ProjectBasics/ProjectForm/ProjectForm.test.tsx
- src/components/Project/ProjectBasics/ProjectForm/ProjectInfoSection.tsx
- src/components/shared/TextAreaField.tsx
- src/forms/useProjectForm.ts
- src/i18n/fi.json
https://futurice.atlassian.net/browse/HKISD-105
The logic of this fix is described in the comment in the code. I noticed that this problem occured also when user was editing a project and not just when they were creating one.
> HKISD-105: disappearing form data

- src/components/Project/ProjectBasics/ProjectForm/ProjectStatusSection.tsx
- src/components/Project/ProjectHeader/ProjectHeader.tsx
- src/components/shared/SelectField.tsx
- src/utils/common.ts
https://futurice.atlassian.net/browse/HKISD-21
The following places should be tested:
- Changing the project phase in the project listing
- The top part of the project form
- A bit lower on the project form
> HKISD-21: fix icons

- src/components/Report/ReportRow.tsx
https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-111
Projects that are in these phases (**proposal, design, completed**) should not be shown in any of the reports.
> HKISD-111: filter projects by their phase

- src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx
- src/components/Report/ReportRow.tsx
- Fix for projects to be shown in the reports
> Release 13.5.2024

- src/components/Report/DownloadPdfButton.tsx
- src/components/Report/PdfReports/ConstructionProgramTableHeader.tsx
- src/utils/reportHelpers.ts
- changed years to be from 2025 instead of 2024
- fixed cost estimate value for projects on the report (was incorrectly budget before)
> HKISD-131: fix years and costEstimate calculation on construction report

- src/hooks/usePlanningRows.ts
- src/interfaces/reportInterfaces.ts
- src/utils/planningRowUtils.ts
- src/utils/reportHelpers.ts
- changed the logic for showing project on the report based on the main class they are under (8 01, 8 04 and 8 08 should have projects in addition to groups and groups are shown as classes there)
- removed empty classes (classes without projects or groups that would be shown on the report) from the report
- ticket: [https://futurice.atlassian.net/browse/HKISD-131](https://futurice.atlassian.net/browse/HKISD-131)
> HKISD-131/construction program report changes

- src/components/Report/PdfReports/ReportTable.tsx
- src/i18n/fi.json
- src/utils/reportHelpers.ts
- added class summary and under 1 million projects summary -rows for the report to classes that the client requested on this ticket (pdf in the ticket's comments): [https://futurice.atlassian.net/browse/HKISD-131](https://futurice.atlassian.net/browse/HKISD-131)
> HKISD-131/construction program report new rows

- src/components/Report/PdfReports/TableRow.tsx
- src/utils/reportHelpers.ts
- client requested to have the yearly budgets instead of the costForecast for the summary rows, so I made that change
- changed the order of the summary rows
> HKISD-131/construction program report summary row changes

- src/components/Report/PdfReports/TableRow.tsx
- src/utils/reportHelpers.ts
- added empty rows after the summary rows for the construction program report
> HKISD-131: feat: add emty rows after the summary rows

- src/hooks/usePlanningRows.ts
- src/interfaces/reportInterfaces.ts
- src/utils/planningRowUtils.ts
- src/utils/reportHelpers.ts
- HKISD-139 fix: missing districts, groups and projects under districtPreviews
> Fix: missing districts, groups and projects under districtPreviews 

- src/utils/reportHelpers.ts
- projects where missing from 8 01
> HKISD-139/construction program report changes

- src/components/Report/DownloadCsvButton.tsx
- src/utils/reportHelpers.ts
- change years to start from 2025 instead of 2024 in the csv for construction report
- Ticket: [https://futurice.atlassian.net/browse/HKISD-142](https://futurice.atlassian.net/browse/HKISD-142)
> HKISD-142: fix: years for construction report csv

- src/components/Report/PdfReports/TableRow.tsx
- src/utils/reportHelpers.ts
- Add bold style for header groups
> fix: HKISD-139 add bold for header groups

- src/interfaces/userInterfaces.ts
- src/mocks/mockUsers.ts
- src/reducers/authSlice.ts
- src/utils/userRoleHelpers.ts
- ticket: [https://futurice.atlassian.net/browse/HKISD-138](https://futurice.atlassian.net/browse/HKISD-138)
- added new user role based on the ticket
- the new katselijat_muut role should have the same permissions as the katselijat role
- for testing, both backend and frontend need to be in the feature branches and other roles need to be commented out
> HKISD-138/katselijat muut user role

- src/utils/reportHelpers.ts
- fixed the issue of groups not showing on the construction report
> fix: groups not showing on the report

- src/utils/reportHelpers.ts
- fixes the issue of missing groups on the construction report
> fix: missing groups on construction report

- src/components/Report/DownloadCsvButton.tsx
- src/components/Report/DownloadPdfButton.tsx
- src/components/Report/PdfReports/ReportTable.tsx
- src/interfaces/planningInterfaces.ts
- src/interfaces/reportInterfaces.ts
- src/utils/planningRowUtils.ts
- src/utils/reportHelpers.ts
- fixed the issue with groups not showing the division on the construction report
> fix: HKISD-139 fix the issue with divisions not showing for groups

- src/components/Report/ReportRow.tsx
- src/i18n/fi.json
- ticket: [https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-153](https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-153)
- removed warranty period projects from the construction report
- other reports already include the warranty period projects
> HKISD-153/takuuaika phase on reports

- src/utils/reportHelpers.ts
- ticket: [https://futurice.atlassian.net/browse/HKISD-147](https://futurice.atlassian.net/browse/HKISD-147)
- fixed the sum rows under "Sörnäistentunneli" (it was caused by the rows having projects directly under the class and the value given to getUnderMillionSummary function only included the children and not projects. Now the whole row is given to the function (includes projects and children)
- fixe the issue were summary rows were showing even though there was nothing else under the class on the report. Now the whole class is not shown if the summary rows are the only rows under it.
- fixed the removing Esirakentaminen-class from the report functionality, cause the old one wasn't working
> HKISD-147: fix summary rows on construction report

- src/components/Report/PdfReports/ReportContainer.tsx
- src/i18n/fi.json
https://futurice.atlassian.net/browse/HKISD-152
Update Strategy report (Toimintasuunnitelmaraportti) 
- Change the title and subtitle
- Add a short description in the title on the Reports page
> HKISD-152/strategy report changes

- src/components/Report/PdfReports/OperationalEnvironmentAnalysisTableHeader.tsx
- src/i18n/fi.json
- src/utils/reportHelpers.ts
https://futurice.atlassian.net/browse/HKISD-111
> HKISD-111: Fixes

- src/components/Report/PdfReports/BudgetBookSummaryTableHeader.tsx
- src/components/Report/PdfReports/DefaultReportFooter.tsx
- src/components/Report/PdfReports/ReportContainer.tsx
- src/i18n/fi.json
- src/utils/reportHelpers.ts
https://futurice.atlassian.net/browse/HKISD-157
To-Do:
> HKISD-157/budget book summary report changes

- src/utils/reportHelpers.ts
- removed classes, that don't have any budgets, from the report
> feat: HKISD-162 remove empty classes from the strategy report

- src/utils/reportHelpers.ts
Show correct TA values (raamiluku) on TA 2024 column
> HKISD-162/Fix strategy report TA values

- src/components/Report/DownloadPdfButton.tsx
- src/components/Report/PdfReports/ReportContainer.tsx
- src/components/Report/PdfReports/StrategyTableHeader.tsx
- src/utils/reportHelpers.ts
https://futurice.atlassian.net/browse/HKISD-165
Fetch 2025 data on Strategy report.
> feat: HKISD-165 fetch next year data for strategy report

- nginx.conf
- src/components/Planning/GroupDialog/GroupProjectSearch.tsx
fix: HKISD-184 add max size for http header
> Release 23.9.2024

- src/components/Report/DownloadCsvButton.tsx
- csv download was still using the forced to frame data
- goes to main cause dev/test pipelines don't work cause there's issues in platta
> fix: HKISD-188 update csv to use coordination view data

- src/components/Report/PdfReports/TableRow.tsx
- src/utils/reportHelpers.ts
- fixed the logic to create the timeline for strategy report
- use year 2025 in filtering the project for the strategy report
> HKISD-188/fix strategy report timeline

- src/components/Report/PdfReports/TableRow.tsx
- src/utils/reportHelpers.ts
- fixed the inverted colours on the strategy report timeline
- fix getProjectPhase function to return the correct project phase
- remove unused getMonth function
> Hkisd 188/fix strategy report timeline

- src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx
- fixed an issue where project was thrown out of group when location data was modified even when the class selection stayed the same
> HKISD-159/group project class data handling

- src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx
- src/utils/common.ts
Updated error handling for a project's estPlanningEnd and estConstructionStart
Removed unnecessary functions in utils.ts
Improved errorhandling if status error is 403
> Hksid 168 update projectmanager save error

- src/components/Planning/GroupDialog/GroupProjectSearch.tsx
- src/forms/useGroupForm.ts
- both groups and projects have "Eri kaupunginosia" location option in the division level
- If the option is selected for a group, it allows projects from all divisions to be added under the group
> HKISD159/enable eri lokaatioita -location option

- src/components/Report/PdfReports/TableRow.tsx
- src/utils/reportHelpers.ts
- changes will be tested in staging before deploying to prod
> Release: Strategy report changes

- src/hooks/useCsvData.ts
- src/utils/reportHelpers.ts
- changed year to be 2025 in the strategy report csv
- changed getting the frame budget to use year 2025
> HKISD-203 change strategy-report csv to use year 2025

- src/utils/reportHelpers.ts
This PR fixes the path in frameBudgetHandler. 
This is an additional fix to https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/285.
> HKISD-213: fix path in frameBudgetHandler

- src/components/Admin/AdminForcedToFrame/AdminForcedToFrame.tsx
- src/i18n/fi.json
- added confirm dialog for updating all forced to frame data
> IO-403: add confirm dialog for updating all forced to frame data

- src/App.tsx
- src/forms/useProjectForm.ts
- ticket: [https://futurice.atlassian.net/browse/HKISD-163](https://futurice.atlassian.net/browse/HKISD-163)
- test by opening a project card and see that the class data loads correctly
> HKISD-163: fix opening project cards directly with a link

- src/hooks/useCoordinationRows.ts
- src/hooks/usePlanningRows.ts
- src/hooks/useUpdateEvents.ts
- src/reducers/planningSlice.ts
Reverts City-of-Helsinki/infraohjelmointi-ui#297
We will forward more important features and fixes from dev to prod first.
> Revert "fix: HKISD-196 set projects if the planning mode is the same as the view"

- src/hooks/useCoordinationRows.ts
- src/hooks/usePlanningRows.ts
- src/hooks/useUpdateEvents.ts
- src/reducers/planningSlice.ts
Reverts City-of-Helsinki/infraohjelmointi-ui#298 that is a revert of the original PR City-of-Helsinki/infraohjelmointi-ui#297
> Re-apply "fix: HKISD-196 set projects if the planning mode is the same as the view""

- src/hooks/useCoordinationRows.ts
- src/hooks/usePlanningRows.ts
- src/hooks/useUpdateEvents.ts
- src/reducers/planningSlice.ts
HKISD-196: fix to set projects if the planning mode is the same as the view
> Release 5.12.2024

- src/components/AuthGuard/AuthGuard.tsx
Fixes the loop issue when the app is opened.
> IO-419/hotfix stuck on planning view

- src/components/Project/ProjectHeader/ProjectHeader.tsx
- src/components/Project/ProjectHeader/styles.css
Disabled project header status so that it can't be removed and not changed on top.
> HKISD-228 Fixed project header to disabled

- src/hooks/useDoubleClick.ts
Ticket: [https://futurice.atlassian.net/browse/HKISD-266](https://futurice.atlassian.net/browse/HKISD-266)
> HKISD-266: change double click latency value to default

- src/components/Project/ProjectBasics/ProjectForm/ProjectHashTags/ProjectHashTags.tsx
- src/hooks/useDoubleClick.ts
- HKISD-266: adjust double click latency
> Release 13.2.2025

- src/components/Report/DownloadCsvButton.tsx
- src/components/Report/PdfReports/ReportContainer.tsx
- src/components/Report/PdfReports/StrategyTableHeader.tsx
- src/components/Report/common.tsx
- src/utils/reportHelpers.ts
https://helsinkisolutionoffice.atlassian.net/browse/IO-412
Use current year data for Ennuste-report.
> IO-412/feat Ennuste raportti current year values

- src/components/Report/PdfReports/ReportContainer.tsx
- src/i18n/fi.json
https://helsinkisolutionoffice.atlassian.net/browse/IO-424
Add a new subtitle.
> IO-424/feat Ennuste report description

- src/components/Search/HkrIdSearch.tsx
- src/components/Search/Search.tsx
- src/components/Search/styles.css
- src/hooks/useSearchTerms.ts
- src/i18n/fi.json
- src/interfaces/formInterfaces.ts
- src/reducers/searchSlice.ts
- src/utils/buildSearchParams.ts
- added search fields for pw id and construction person
- ticket: [https://helsinkisolutionoffice.atlassian.net/browse/IO-408](https://helsinkisolutionoffice.atlassian.net/browse/IO-408)
- API PR: [https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/249](https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/249)
> IO-408: new fields for search

- src/services/projectServices.ts
- fixed the urls to match the url patterns backend accepts
- not the cleanest solution, but will refactor if we notice this helps with the issue :)
> fix urls for getting pages for projects to reports

- src/components/Report/ReportRow.tsx
> change limit value for pagination of projects

- src/components/Report/DownloadCsvButton.tsx
- src/components/Report/DownloadPdfButton.tsx
- src/components/Report/PdfReports/OperationalEnvironmentCategorySummary.tsx
- src/components/Report/PdfReports/ReportTable.tsx
- src/components/Report/ReportRow.tsx
- src/components/Report/common.tsx
- src/hooks/useCsvData.ts
- src/interfaces/projectInterfaces.ts
- src/interfaces/searchInterfaces.ts
- src/services/projectServices.ts
- src/utils/reportHelpers.ts
Reverts City-of-Helsinki/infraohjelmointi-ui#345
> Revert "Release 3.4.2025"

- src/components/Report/DownloadCsvButton.tsx
- src/components/Report/DownloadPdfButton.tsx
- src/components/Report/PdfReports/OperationalEnvironmentCategorySummary.tsx
- src/components/Report/PdfReports/ReportTable.tsx
- src/components/Report/ReportRow.tsx
- src/components/Report/common.tsx
- src/hooks/useCsvData.ts
- src/interfaces/projectInterfaces.ts
- src/interfaces/searchInterfaces.ts
- src/services/projectServices.ts
- src/utils/reportHelpers.ts
Reverts City-of-Helsinki/infraohjelmointi-ui#348
> Revert "Revert "Release 3.4.2025""

- src/components/Report/DownloadCsvButton.tsx
- src/components/Report/DownloadPdfButton.tsx
- src/components/Report/PdfReports/OperationalEnvironmentCategorySummary.tsx
- src/components/Report/PdfReports/ReportTable.tsx
- src/components/Report/ReportRow.tsx
- src/components/Report/common.tsx
- src/hooks/useCsvData.ts
- src/interfaces/projectInterfaces.ts
- src/interfaces/searchInterfaces.ts
- src/services/projectServices.ts
- src/utils/reportHelpers.ts
Reverts City-of-Helsinki/infraohjelmointi-ui#351
> Revert "Revert "Revert "Release 3.4.2025"""

- src/components/AuthGuard/AuthGuard.tsx
https://futurice.atlassian.net/browse/HKISD-183
> HKISD-183/redirect viewer-other to planning view

- src/components/TopBar/TopBar.tsx
https://futurice.atlassian.net/browse/HKISD-273
> fix: HKISD-273 header logo and title navigates to correct page

- src/forms/useProjectForm.ts
- src/views/ProjectView/ProjectView.tsx
- fixed an issue where if project card was opened with a link, class information was missing
- ticket: [https://futurice.atlassian.net/browse/HKISD-293](https://futurice.atlassian.net/browse/HKISD-293)
> HKISD-293: fix project card missing information when opened with a link

- src/components/Project/ProjectBasics/ProjectForm/ProjectInfoSection.tsx
- ticket: [https://futurice.atlassian.net/browse/HKISD-221](https://futurice.atlassian.net/browse/HKISD-221)
>  IO-221 change entity name validation to allow 80 chars instead of 30

- src/hooks/useCsvData.ts
- src/utils/reportHelpers.ts
- added csv download for rakentamisohjelmna ennuste report
> IO-448: rakentamisohjelman ennusteraportti CSV

- src/components/Report/PdfReports/ReportContainer.tsx
- src/components/Report/PdfReports/TableRow.tsx
- src/components/Report/PdfReports/reportHeaders/BudgetBookSummaryTableHeader.tsx
- src/components/Report/PdfReports/reportHeaders/ConstructionProgramTableHeader.tsx
- src/components/Report/PdfReports/reportHeaders/OperationalEnvironmentAnalysisTableHeader.tsx
- src/i18n/fi.json
- src/utils/reportHelpers.ts
- adds missing kilo euro texts on table header rows
- remove unnecessary info text from forecast report footer
- on translation file move million euro text on shared report strings
> IO-450/report header kilo euros

- src/components/Report/DownloadPdfButton.tsx
- src/hooks/useCsvData.ts
- src/interfaces/reportInterfaces.ts
- src/utils/reportHelpers.ts
- added sap numbers to construction report
- add sap numbers to construction report and construction forecast csv:s
> IO-457: add SAP number to construction report and csv

- src/components/Report/PdfReports/reportHeaders/ConstructionProgramForecastTableHeader.tsx
- src/i18n/fi.json
ticket: https://helsinkisolutionoffice.atlassian.net/browse/IO-415
> feat: IO-415 small text changes to reports view and add line breaks to construction program forecast report

- src/components/Report/DownloadPdfButton.tsx
- src/components/Report/PdfReports/ReportContainer.tsx
- src/components/Report/PdfReports/ReportTable.tsx
- src/components/Report/PdfReports/TableRow.tsx
- src/components/Report/ReportRow.tsx
- src/components/Report/common.tsx
- src/hooks/useCsvData.ts
- src/i18n/fi.json
- src/interfaces/reportInterfaces.ts
- src/utils/reportHelpers.ts
Add new report which is similar to construction program report but shows forced to frame numbers.
https://helsinkisolutionoffice.atlassian.net/browse/IO-456
> feat: IO-456 construction program forced to frame report

- src/utils/reportHelpers.ts
https://helsinkisolutionoffice.atlassian.net/browse/IO-456
> fix: IO-456 Remove under one million summary rows from construction program reports

- src/components/Project/ProjectBasics/ProjectForm/ProjectForm.test.tsx
- src/components/Project/ProjectBasics/ProjectForm/ProjectResponsiblePersonsSection.test.tsx
- src/components/Project/ProjectBasics/ProjectForm/ProjectResponsiblePersonsSection.tsx
- src/components/TopBar/TopBar.test.tsx
- src/components/shared/SelectField.tsx
- src/forms/useProjectForm.test.tsx
- src/forms/useProjectForm.ts
- src/hooks/useLocationBasedProgrammer.ts
- src/interfaces/classInterfaces.ts
- src/interfaces/common.ts
- src/interfaces/formInterfaces.ts
- src/mocks/mockLists.ts
- src/reducers/listsSlice.ts
- src/services/listServices.test.ts
- src/services/listServices.ts
- src/utils/common.ts
- src/utils/locationProgrammerUtils.ts
- src/utils/mockGetResponseProvider.ts
- src/utils/programmerUtils.test.ts
- src/utils/programmerUtils.ts
* Enable programmer dropdown in project form
* Add default programmer selection based on class hierarchy
* Add tests for programmer selection and defaults
* Filter out empty programmer ('Ei Valintaa') from selection dropdowns
* Implement location-based programmer selection based on suurpiiri field
https://helsinkisolutionoffice.atlassian.net/browse/IO-411
> feat: IO-411 Enable programmer selection with default values
