City-of-Helsinki/infraohjelmointi-ui

src/components/Planning/PhaseDialog/PhaseDialog.tsx, src/reducers/projectSlice.ts
- close phase dialog when patching phase
- remove notification when patching phase from planning list
- update list view phase when patching phase from project card form
- removed unnecessary debugs from projectCardBasics.test.tsx
- removed timeout extensions from projectCardBasics.test.tsx
=> Story/io 18/project phase to planning list

src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectFormBanner.tsx, src/components/shared/DateField.tsx
**Needs to be merged after the project form field validations PR: https://github.com/City-of-Helsinki/infraohjelmointi-ui/pull/57**
- fixes the date picker going back to the previous selection and year by disabling the onBlur event for ProjectForm while the date picker is open
=> Story/io 303/date picker fix

src/components/SearchResults/SearchResultsCard.tsx, src/hooks/useSearchResultsList.ts, src/i18n/fi.json, src/interfaces/searchInterfaces.ts, src/mocks/mockSearch.ts, src/views/SearchResultsView/SearchResultsView.test.tsx
- Added a tag for projects that are not programmed
- Navigate not programmed projects to project form instead of planning view 
- **Needs to be merged with the backend fix: https://github.com/City-of-Helsinki/infraohjelmointi-api/tree/fix/search-results-projects-response**
=> Story/io 316/direct non programmed projects to project form from search results

src/components/Planning/PlanningTable/PlanningRow/PlanningForecastSums.tsx, src/hooks/useNumberInput.ts
With this, users can
- add negative numbers
- send value updating request only when the input field includes a value when closing
- remove text from input field (before it did not allow users to remove, replaced empty input field with "0"
Issue:
- when clicking the button (number) which opens the input field, it will be empty _if_ the field was left empty previously
- um, huh? What do you mean? How to test this?
1) Open a TA field
2) Clear it and close the input field (by clicking on somewhere)
3) Re-open the same input field
4) Because it was left empty, it stays empty
- What should happen?
- When user clears the input field, closes it, and re-opens it, it should show the same value as the button text does.
=> Story/io 373/enable negative values ta muutos

src/hooks/useSummaryRows.ts, src/views/PlanningView/PlanningView.test.tsx
- Modified getPlanningRowTitle function to return the title based on current year and not based on index (for example: previously "kuluva TA" title was always given to the selected year and now it's give to the actual current year)
- Titles should now change automatically when the year changes
- Ticket: [https://helsinkisolutionoffice.atlassian.net/browse/IO-57](https://helsinkisolutionoffice.atlassian.net/browse/IO-57)
- "TP" title was not added cause "tilinpäätös" functionality is not implemented yet
=> IO 57: title changes related to year change

src/App.tsx, src/components/AuthGuard/AuthGuard.tsx
- user is now redirected to planning view after login instead of the 404 error page
- Ticket: [https://futurice.atlassian.net/browse/HKISD-7](https://futurice.atlassian.net/browse/HKISD-7)
=> Fix: 404 error page after login

src/components/Planning/PlanningTable/PlanningRow/ProjectRow/projectCellUtils.ts, src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx, src/hooks/useProjectRow.ts, src/utils/dates.ts
- Added functionality to move budgets from finance years when they are left out of project schedule after modifying the schedule from a project card
- Fixed a bug when trying to delete an overlap year, that isn't the end or the start of the timeline, from the timeline
- Can be tested by modifying the project schedule from a project card and seeing that the budgets move accordingly in the timeline (planning or coordinator views)
- Try to also delete an overlap year from the timeline and check that the budget moved correctly and year was deleted.
=> functionality to move budgets when out of project schedule

src/components/Planning/PlanningTable/PlanningRow/ProjectRow/ProjectCell.tsx
- on Programming view (Ohjelmointi), if cell is activated, but the number is not changed, the loading icon stays endlessly.
=> fix issue with loading if a cell is activated but number not changed

src/i18n/fi.json
Option in project card was before "Puisto tai taitorakenne" and this was fixed to be only "Puisto". 
[HKISD-17](https://futurice.atlassian.net/browse/HKISD-17)
=> Change name of the option in project card

src/components/Planning/PlanningTable/PlanningRow/PlanningRow.tsx
https://futurice.atlassian.net/browse/HKISD-26
I added this `!search.includes("subClass")` condition for the check so that all the numbers in the Eteläinen suurpiiri row (and  in other equivalent rows) are again visible on the subClass level. We will need to investigate this issue more as the framebudget is not available on the subClass level in the frontend as it's available on the higher level.
=> HKISD-26 / HKISD-12: Add check for the table level

src/components/Project/ProjectBasics/ProjectForm/ProjectForm.test.tsx, src/components/shared/ListField.tsx, src/utils/common.ts
- budget field had € even though it was supposed to be keur
- related to ticket [https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-24](https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-24)
=> change budget field in project card to be keur

src/hooks/useCoordinationRows.ts
- Meluesteet came before districts in coordinator view -> is now the other way around
- related to ticket [https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-24](https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-24)
=> filter colletiveSubLevels before districts in coordinator view

src/hooks/usePlanningRows.ts
- https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-26
- fixed frameBudget not showing correctly in planning view when opening a district so that it becomes the top level
=> HKISD-26/fix frame budget in planning view

src/views/ProjectView/ProjectView.tsx
- if user was creating a new project and another user saved updated project, a new project's form got updated project's information
- this feature is created to keep project form updated if two users are updating the same project at the same time, but in this case it was acting incorrectly
- checks correctly if selected project is empty
=> don't update project form if another user edits different project

src/components/shared/DateField.tsx
- https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-46
- changed caledars to show dates until the end of 10th year from now instead of just exactly 10 years from now
- calendar component is from hds and they default it to 10 years from now, so it's not possible to have it be limitless. We could set the end date to very far future, but I don't know if it's a better solution than this, since it still wouldn't be limitless
=> HKISD-46/project card calendar

src/i18n/fi.json
- e.status will return "undefined" if UI can't connect to API
- show undefined as "Virhe"
Related: #146 
Ticket: https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-53
=> HKISD-53: Add missing 'undefined' notification error title

src/App.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectFormBanner.tsx
https://futurice.atlassian.net/browse/HKISD-48
When user was deleting a project, the numbers were not updated because they were cached in the backend (PR for that: https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/117). In addition to removing caching we have to download the data again after user deletes the project because otherwise the data won't be updated.
I was also thinking if we should do something else than delete the cache for the summed finances but then again e.g. adjusting the length of the cache does not really solve this issue either as the data should be updated when the project is deleted, any opinions?
=> HKISD-48: Fix a calculating issue

README.md, src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx
- Fixed a bug where in moving the budgets to be within the project schedule when the project schedule changes the budget for new start year was set to NaN
- Related to this fix, theres also a fix in the backend. I refactored the backend code so that it's not limited to 10 years of finance years. PR: https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/118
- added instruction on how to add env variables to azure
=> HKISD-28: fix schedule change in project form

src/App.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectHashTags/HashTagsContainer.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectHashTags/ProjectHashTags.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectInfoSection.tsx, src/hooks/usePromptConfirmOnNavigate.ts
https://futurice.atlassian.net/browse/HKISD-34
When user was creating a new project, they weren't able to add hashtags for it because the hashtags were tried to be saved to a specific project right away but there were no project to which they could've been saved into.
I tried to save the hashtags to the same place where the unsaved values are stored but it was not possible (or at least not very easy) to do because of the structure of the code and I think that the hashtags were having some own state for them so they were not included to the other values of the form. I ended up creating a solution where the hashtags are temporarily stored into local storage when user is creating a project and when they want to save the project, the values are taken from the local storage. (I was also …
=> HKISD-34: fix hashtag saving in new projects

src/components/Project/ProjectBasics/ProjectForm/ProjectStatusSection.tsx
https://futurice.atlassian.net/browse/HKISD-23
The construction phase detail (rakennusvaiheen tarkenne) was previously a required field in warranty phase (takuuaika) and completed phase (valmis / ylläpidossa). With these changes it's not anymore required in takuuaika and valmis / ylläpidossa fields.
=> HKISD-23: fix construction phase detail validation

src/hooks/usePromptConfirmOnNavigate.ts
https://futurice.atlassian.net/browse/HKISD-58
When user was on the project form and had edited some fields and then clicked some of these sidebar elements in order to move to a specific part of the form, the user was asked if the wanted to continue. I was able to get the value of the target url from args in usePromptConfirmOnNavigate that handles this confirmation modal but I'm not entirely sure if the args will always have the value in the future for example if we update the react-router package but I couldn't find the information form anywhere else either.
=> HKISD-58: fix confirm modal visibility on project form

src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx
https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-60
The project disappeared because it belonged to some group and when the user changed its class in the project form, the group that the project belonged to didn't exist in the new class --> we will have to delete the group information from the project.
I also noticed another problem: if the project was under some district and the user changed the class, the district had to be removed also or the project would exist under that district in that new class that it was saved into even though that class didn't have any districts inside of it. 
When you test these changes, you might need to refresh the page after updating the project values as the  project views don't necessarily get updated.
=> HKISD-60: disappeared project

src/components/Planning/PlanningTable/PlanningRow/PlanningRow.tsx
https://futurice.atlassian.net/browse/HKISD-54
I was able to reproduce this issue by
1. going to a project form
2. chose a district as a subclass at Hankkeen kustannustiedot
3. then a bit lower on the form at Hankkeen sijainti, chose the same district as project's location
4. went back to the planning view using the page's own functions.
For me it didn't render the district twice if I changed the subclass and location values more than once on the project form before saving!
The extra row's type was districtPreview and I think that it should only exist on a subClass level and the solution is based on that assumption. I could find districtPreview rows e.g. here where they are on a subClass level:
=> HKISD-54: Fix for not to render the district twice

src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx
At the moment there is a change, that user can create multiple projects by clicking the button multiple times.
With adding a loading spinner, it disables (hides behind the element) the button after the button is clicked once.
=> Add loading icon when submitting a new project

src/components/Report/DownloadPdfButton.tsx, src/components/Report/ReportRow.tsx
- Removes projects fetch from reports for testing purposes, will be reverted once we have tested the functionality
- only for dev environment
=> Remove projects fetch from reports for testing purposes in dev environment

src/utils/calculations.ts, src/utils/reportHelpers.ts
I fixed the substring issue with the calculations and added a check for the names of classes. We should not show items that name does not start with some number or a letter and a space on the lower levels. This check is done for every class now but I checked that in forced to frame view data, every class should start either with numbers or a letter and a space in the higher levels so the check can be done to those levels too.
=> IO-338: added fixes

src/utils/reportHelpers.ts
The extra rows were not included to the if sentence so they were shown still.
=> IO-336: fix row hiding

src/components/Project/ProjectBasics/ProjectForm/ProjectInfoSection.tsx
https://futurice.atlassian.net/browse/HKISD-86
The maximum length of this field is 1000 characters, which hasn't been communicated anywhere. This rule will add a notification text when the user exceeds the maximum length. We should check the other fields too if there are similar restrictions that could be communicated by using the already existing rules.
=> HKISD-86: description length

src/components/Report/DownloadCsvButton.tsx, src/components/Report/DownloadPdfButton.tsx, src/components/Report/PdfReports/ReportTable.tsx, src/components/Report/PdfReports/TableRow.tsx, src/components/Report/ReportRow.tsx, src/hooks/usePlanningRows.ts, src/interfaces/planningInterfaces.ts, src/interfaces/reportInterfaces.ts, src/utils/calculations.ts, src/utils/reportHelpers.ts, src/views/ReportsView/ReportsView.tsx
- Report now has all groups that have a costEstimateBudget that is grater than 1 million and have at least one project that is in planning or construction phase in the next three years
- It should also have projects that have a costEstimateBudget that is grater than 1 million and don't belong to a group
- changed masterClass names to be in uppercase if the report is constructed from coordination view data
- ticket: [https://helsinkisolutionoffice.atlassian.net/jira/software/c/projects/IO/boards/302?selectedIssue=IO-334](https://helsinkisolutionoffice.atlassian.net/jira/software/c/projects/IO/boards/302?selectedIssue=IO-334)
=> IO-334/fixes for construction report

src/utils/calculations.ts
ticket:[https://futurice.atlassian.net/browse/HKISD-82]( https://futurice.atlassian.net/browse/HKISD-82)
- frame budget sums were previously the same as programmed budgets sum
=> HKISD-82: fix calculating frame budget sums

src/services/projectServices.ts, src/views/SearchResultsView/SearchResultsView.test.tsx
https://futurice.atlassian.net/browse/HKISD-120
When user tried to use next or previous buttons on the search page, they got an error. I think that ensuring we use the same beginning in the search url, the problem could be fixed. If next / previous buttons were clicked, the search url started with **http** instead of **https**, which caused the error. The `req.fullPath` was used with the next / previous buttons and the `${REACT_APP_API_URL}/projects/search-results/?${req.params}&limit=${req.limit}&order=${req.order}` was used when user clicked the numbers.
=> HKISD-120: fix search button

src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx
- Moving planningStartYear and constructionEndYear from the project card didn't move the budgets to the closest year within the new schedule -> should be fixed now
- Ticket (specs of this problem in the comments): [https://futurice.atlassian.net/browse/HKISD-87](https://futurice.atlassian.net/browse/HKISD-87)
=> HKISD-87/fix moving budgets creates zeros issue

src/components/Project/ProjectBasics/ProjectForm/ProjectScheduleSection.tsx
This PR fixes bug in yearCell. Year changing was not possible due to missing check for if constructionEndYear isDirty.
=> Fix: HKISD-124 fix bug in construction end year changing

src/hooks/usePlanningRows.ts, src/interfaces/reportInterfaces.ts, src/utils/planningRowUtils.ts, src/utils/reportHelpers.ts
- districts that the user has to open in planning view to be able to see groups and projects were missing from the construction report (for example jalankulun ja pyöräilyn väylät didn't have anything under it)
- ticket: [https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-139](https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-139) bug reported in the comments
=> HKISD-139 fix: missing districts, groups and projects under districtPreviews

src/utils/reportHelpers.ts
- change , to . before converting to float in construction report, cause parseFloat function doesn't understand , as a decimal point
=> fix: change , to . before converting to float in construction report

src/components/Project/ProjectBasics/ProjectForm/ProjectForm.test.tsx, src/utils/reportHelpers.ts
Report shows summary with values that uses dot as decimal separator.
- change dot decimal separator to comma.
=> fix: use comma as a decimal separator on construction reports

src/components/Project/ProjectBasics/ProjectForm/ProjectForm.test.tsx, src/components/Report/DownloadCsvButton.tsx, src/components/Report/DownloadPdfButton.tsx, src/components/Report/PdfReports/ReportContainer.tsx, src/components/Report/PdfReports/ReportTable.tsx, src/components/Report/ReportRow.tsx, src/interfaces/reportInterfaces.ts, src/utils/reportHelpers.ts
https://futurice.atlassian.net/browse/HKISD-111
There were some issues with the projects that are in the warranty phase. I wrote an explanation about the problem to the ticket. To solve the issue, I had to check which projects are in the warranty phase and then add calculation logic in order to get the budgets of those projects to be added to the sum levels for example in the image below (e.g. **8 01**, **8 01 03** and **8 01 03 01**).
**This can be tested in the following way:**
1. go to the coordination view and make sure that there is a project with some budget in the current year. Then you should take a screenshot in which you can see the numbers of different levels (e.g. **8 03**, **8 03 01** and **8 03 01 01**)
2. Go to change the project to the warranty phase
3. Go download the …
=> HKISD-111: Fix operational environment analysis report

src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectScheduleSection.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectStatusSection.tsx, src/i18n/fi.json, src/interfaces/common.ts, src/reducers/authSlice.ts, src/reducers/listsSlice.ts
- changed project manager role's accesses so that they can only modify project phase forwards
- can be tested by setting the project manager role to ad_groups in authSlice -> you can see the UI as if you'd only have the project manager role
=> HKISD-134/phase edit for project manager

src/utils/reportHelpers.ts
https://futurice.atlassian.net/browse/HKI-147
With this change, missing Kalasatama-Pasila rows "Muut alle 1 milj. euron investointihankkeet" and "Hankkeet yhteensä" rows will be added.
=> HKISD-147/Add Kalasatama-Pasila with extra rows on construction report

src/components/Report/PdfReports/StrategyTableHeader.tsx, src/components/Report/PdfReports/TableRow.tsx, src/utils/reportHelpers.ts
- fix colours when end month is different than December, and the end year is different than the current year
- add colours for rows based on row types (class, subClass, project, group, ...)
- show previously hidden groups on the report
- show TA "raamiluku" values
To-do
- Hide rows that does have "raami" 0
- Hiding classes that has TA value 0 requires more investigation and will not be done on this PR.
Testing
- Open Reports
- Download strategy Toimintasuunnitelma PDF and CSV files
- Should include the same TA and TS values
- TA values are only visible for higher classes
- TS values for each classes and projects
- PDF file
- Stylized rows
Ticket and conversation: https://futurice.atlassian.net/browse/HKISD-152
=> HKISD-152/toimintasuunnitelma report changes

src/components/Planning/PlanningTable/PlanningRow/ProjectRow/ProjectYearSummary/ProjectYearSummaryTable.tsx
Updated formatting of SAP-numbers
Sap-numbers are now displayed in kiloeuros (thousands of euros) in the overview.
Rounding: Numbers are rounded to the nearest thousand. Example: 9,501 euros → 10 000 euros.
Localization: Applied French formatting with spaces as thousand separators.
=> HKISD-151 Update formatting of sap numbers

src/interfaces/reportInterfaces.ts, src/utils/reportHelpers.ts
- all classes, groups and projects named "Esirankentaminen" were missing from the construction report, though only 801/Esirankentaminen class was supposed to be missing
- fixed by comparing the path instead of the name when removing the row from the report
- ticket: [https://futurice.atlassian.net/browse/HKISD-164](https://futurice.atlassian.net/browse/HKISD-164)
=> HKISD-164/projects missing from construction report

src/components/AuthGuard/AuthGuard.tsx, src/components/Planning/PlanningTable/PlanningRow/ProjectRow/ProjectHead.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectFinancialSection.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectHashTags/HashTagsContainer.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectHashTags/ProjectHashTags.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectInfoSection.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectLocationSection.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectProgramSection.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectResponsiblePersonsSection.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectScheduleSection.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectStatusSection.tsx, src/components/Project/ProjectHeader/ProjectHeader.tsx, src/components/Project/ProjectHeader/ProjectNameFields.tsx, src/components/ProjectDetailsForm/projectDetailsForm.tsx, src/components/shared/DateField.tsx, src/components/shared/FormFieldLabel.tsx, src/components/shared/OverrunRightField.tsx, src/components/shared/RadioCheckboxField.tsx, src/components/shared/SelectField.tsx, src/components/shared/TextField.tsx, src/utils/userRoleHelpers.ts
- ticket: [https://helsinkisolutionoffice.atlassian.net/browse/IO-387](https://helsinkisolutionoffice.atlassian.net/browse/IO-387)
- viewer role can now access project cards in a read only mode
- using search / seeing search results is also allowed for them
-UI and API need to be in the feature branches (API PR: [https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/162](https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/162)
- change your role to viewer only in both
-> for API, go to BaseViewSet.py file and remove all other role checks except for IsViewer from the list -> permission_classes should only have the IsAuthenticated and IsViewer
-> for UI, go to authSlice.ts and uncomment the viewer role/roles from ad_groups array, but leave all other roles commented out
- …
=> feat: IO-387/project card for viewers

src/components/Planning/GroupDialog/GroupProjectSearch.tsx
- Fixed a bug where group's project search allowed to add the same project to the group multiple times.
- Not directly causing issues on ticket HKISD-159, but was found while working on that ticket
=> fix:  group allows to select same project multiple times

nginx.conf
Increase the size of http header 
Ticket: [HKI-184](https://futurice.atlassian.net/jira/servicedesk/projects/HKI/queues/custom/238/HKI-184 )
Helsinki-profiili made keyloak updates on 16.9.2024 and that increased the amount of groups in users AD_groups. That was causing login problems for many people. Users with too many ad_groups got "pääsy evätty" from infratool as the token was not valid. 
Helsinki-profiili advised to set http header size bigger, to allow more groups in user accounts. 
large_client_header_buffers 4   32k; is added as helsinki-profiili advises.
=> Add max size for http header

src/components/Report/DownloadPdfButton.tsx, src/i18n/fi.json
- temporary changes strategy report to fetch data from coordination view instead of forced to frame view
- will be changed back ones the feature to update forced to frame view from planning/coordination view is implemented
- goes directly to main, because dev/test pipelines aren't currently working cause of issues in platta
=> HKISD-188 change strategy report to fetch coordination view data

src/components/Planning/GroupDialog/GroupProjectSearch.tsx, src/forms/useGroupForm.ts, src/utils/common.ts
- ticket: [https://futurice.atlassian.net/browse/HKISD-159](https://futurice.atlassian.net/browse/HKISD-159)
- Fixed the issue where projects are thrown out of group when the location data of the group is changed, even when the project should be allowed to stay inside the group (there's no location conflict after the change)
=> fix: HKISD-159 projects thrown out of group when location data matches

src/forms/useGroupForm.ts
- added logic to handle "Eri suurpiirejä" location option to district options for projects and groups
- API PR for adding the option to the backend: [https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/187](https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/187)
For testing:
- Add the location option with the instructions in the API PR and after that, test the logic in the UI
=> HKISD-159: add eri suurpiirejä location option

src/components/Planning/GroupDialog/GroupProjectSearch.tsx, src/utils/planningRowUtils.ts
- changed the logic of GroupDialog's project search so that if "Eri suurpiirejä" is selected as the district it's the same as if no district was selected
- same for "Eri kaupunginosia" but with division
- changed the logic of fetching projects for the planning view so that projects don't have to be directly under subClass to be fetched to enable showing projects with location information under subClasses when they are inside a group without location information that is under a subClass.
=> HKISD-159: fix groupDialog project search and showing projects in hierarchy

src/components/Project/ProjectBasics/ProjectForm/ProjectFinancialSection.tsx, src/i18n/fi.json, src/utils/calculations.ts, src/utils/validation.ts
**Removed**: Fixed round cost estimate budget number to remove decimal. Original problem solved via backend.
**Added**: Validation for costForecast added, only whole numbers are now allowed
=> HKSID-133 Fixed round cost estimate budget number to remove decimal

src/i18n/fi.json, src/utils/reportHelpers.ts
- If project has not named planning person ("vastuuhenkilö"), in strategy report (toimintasuunnitelma) there will be text "Odottaa nimeämistä" (waiting for naming) in project manager column in strategy report. Previously those were empty if responsible person was not named.
=> HKISD-208: feat add waiting for name in strategy report if project manager is not named

src/components/Report/PdfReports/TableRow.tsx, src/interfaces/reportInterfaces.ts, src/utils/reportHelpers.ts
https://futurice.atlassian.net/browse/HKISD-207
The strategy report has style issues. The hierarchy level "sublevel district" had an incorrect color, and the "collective sublevel" color was missing. This PR fixes the colors to be the same as on the hierarchy view.
=> fix: add a new and update existing hierarchy colours on strategy report

src/App.tsx, src/components/Admin/AdminForcedToFrame/AdminForcedToFrame.tsx, src/components/Planning/PlanningTable/PlanningRow/PlanningCell.tsx, src/components/Planning/PlanningTable/PlanningRow/PlanningForecastSums.tsx, src/i18n/fi.json, src/interfaces/adminInterfaces.ts, src/interfaces/classInterfaces.ts, src/reducers/appStateValueSlice.ts, src/services/appStateValueServices.ts, src/services/projectServices.ts, src/store.ts, src/views/AdminView/AdminView.test.tsx
- added forced to frame -view's status control section to admin view
- added functionality to update forced to frame budgets and schedules for projects, classes and locations (bulk update and update per project/class/location whenever connection between views is set to open and some budget or schedule data is modified in coordinator view)
- ticket: [https://helsinkisolutionoffice.atlassian.net/browse/IO-403](https://helsinkisolutionoffice.atlassian.net/browse/IO-403)
- API PR: https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/197
=> IO-403 & IO-353/forced to frame admin view

src/components/Report/DownloadCsvButton.tsx
- strategy report had an issue where sometimes the TA and TS numbers on the report had thousand separator that caused Excel to not understand that the column has numbers
- ticket: [https://futurice.atlassian.net/browse/HKISD-217](https://futurice.atlassian.net/browse/HKISD-217)
=> HKISD-217: remove spaces from csv numbers

src/App.tsx, src/components/Report/DownloadCsvButton.tsx, src/components/Report/DownloadPdfButton.tsx, src/components/Report/PdfReports/ReportContainer.tsx, src/components/Report/PdfReports/ReportTable.tsx, src/components/Report/PdfReports/TableRow.tsx, src/components/Report/ReportRow.tsx, src/hooks/useCoordinationRows.ts, src/hooks/useCsvData.ts, src/hooks/useUpdateEvents.ts, src/i18n/fi.json, src/interfaces/reportInterfaces.ts, src/reducers/groupSlice.ts, src/services/groupServices.ts, src/utils/reportHelpers.ts
Create new report that uses Strategy report but uses "Sovittu budjetti" data.
To-Do:
Bugs:
=> IO-401/strategy report from sovitettu budjetti data

src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx
Changing the data from where project's class info is taken. Previously if-loop was never reached because class info was taken from updated project info (=new class info) instead of previous class info. 
You have a group that has for example location 8 03 Kadut ja liikenneväylät - Uudisrakentaminen - Eteläinen suurpiiri. And in that group you have projects that has same classes chosen. Project has projectGroup_id in database. 
Then go to project card and change classes for this project to be different from what group has. For example change classes to be 8 04 Puistot ja liikunta-alueet - Uudet puistot - Läntinen suurpiiri. 
Before problem was that projectGroup_id was not emptied after projects classes changed to be different than group's. This caused a situation, that project could not be …
=> HKISD-199: fix emptying project's group id 

src/components/AuthGuard/AuthGuard.tsx
https://helsinkisolutionoffice.atlassian.net/browse/IO-419
Currently when an user opens the app, after different checks it finally redirects them to the root domain. 
This change redirects an user to `/planning` view if they authenticated successfully, they have correct access rights, and they didn't use an URL that redirects to different page.
When opening the local environment `http://localhost:4000`, it should redirect to `localhost:4000/planning` view.
=> feat: IO-419 redirect to planning view as a default

src/components/Project/ProjectBasics/ProjectForm/ProjectForm.test.tsx, src/components/shared/ListField.tsx, src/utils/mockGetResponseProvider.ts
Adding spaces as thousand separators to sap values and budget value in project card. 
Using function formatNumberToContainSpaces from common.ts. Fixing also tests to use thousand separated values and found one missing case in mockGetResponseProvider.ts.
=> Add thousand separator to sap values in project card

src/components/Search/FreeSearchForm.tsx
On Search view that opens from "Haku", you can remove a search word under "Mitä haet?" if there is only one on the list. The issue appears if the list has more than one search word.
The reason why this happened is the currect selector sees all search words as one text, and tries to find this from the `formValue` object. This fix selects correct element's text and uses it to remove the property from the object.
How to test before and after: Open Haku search view and add multiple search words. Try to remove one element by clicking the element.
=> HKISD-254: Fix search remove selected words

src/hooks/usePlanningRows.ts
When an user returns from the Search results view back to hierarchy view, it might create two separate projects-fetches to backend. Depending on which one of requests finishes last, it could cause the hierarchy view to populate projects and then remove all projects. Why this happens is because the last fetch loads projects that are for different hierarchy view.
To prevent unnesessary fetches, the logic checks the page with lowest class/district/group ID is the same as selected lowest class/district/group ID set in state.
How to test before and after:
- Open Search view and search two or more different projects. Projects need to be under different hierarchy classes/districts
- From Search results view, select one of the results. It is 50/50 chance will projects appear and then quickly …
=> fix: HKISD-196 fetch projects only if the view is correct

src/components/Project/ProjectBasics/ProjectForm/ProjectHashTags/ProjectHashTags.tsx
Fixes an issue where a hashtag (tunniste) can't be removed on the project card view.
=> HKISD-259: fix remove hashtags on the project view

src/components/Search/FreeSearchForm.tsx, src/utils/buildSearchParams.ts
- ticket: https://futurice.atlassian.net/browse/HKISD-224
- previously search only returned one project or group with same name even when there actually was more (no projects or groups with duplicate names where returned)
- you can test by creating multiple projects and groups with same name and see that search results has all of them when you search with the name
- you also need the API PR for testing: [https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/235](https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/235)
=> HKISD-224: search groups and projects with same name

src/components/Search/Search.tsx, src/forms/useSearchForm.ts
- ticket: [https://futurice.atlassian.net/browse/HKISD-119](https://futurice.atlassian.net/browse/HKISD-119)
- fixed the issue partly by fixing the filtering of class selection in the search form
- class options are now filtered based on the higher levels. For example if you select a master class, class options only has classes under that master class
=> HKISD-119: fix filtering classes based on users selections

src/forms/useProjectForm.ts, src/reducers/loaderSlice.ts, src/views/ProjectView/ProjectView.tsx
- ticket: [https://futurice.atlassian.net/browse/HKISD-269](https://futurice.atlassian.net/browse/HKISD-269)
- if a user was creating a new project or editing an existing one and someone else made a finance update, the project card was cleared
- can be tested by opening the infratool in two windows and editing or creating a new project but not saving and in the other window editing some budgets from the timeline
=> HKISD-269: fix project card being cleared

src/forms/useSearchForm.ts, src/hooks/useMultiClassOptions.ts, src/hooks/useMultiLocationOptions.ts, src/utils/buildSearchParams.ts
- location filters in search used the locations from the hierarchy, which caused the lists to have multiple duplicates and missing options
- changed to use the same location options as the project card has
- API PR: https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/246
=> HKISD-119: change location filter to use project card location lists

src/hooks/useMultiClassOptions.ts, src/hooks/useMultiLocationOptions.ts
- ticket: [https://futurice.atlassian.net/browse/HKISD-119](https://futurice.atlassian.net/browse/HKISD-119)
- duplucate class and location options now have the parent class/location after it
- for example "Esirakentaminen" is now "Esirakentaminen (8 01 Kiinteä omaisuus)" and "Esirakentaminen (8 08 Projektialueiden infrarakentaminen)"
- location options has the same fix
=> HKISD-119: fix dublicate classes search issue

src/components/Report/PdfReports/TableRow.tsx
A fix that will change the cell background if the value is less than -200 or more than 200.
=> fix: IO-412 red background if the diff is more than the threshold value

src/components/Report/ReportRow.tsx, src/interfaces/projectInterfaces.ts, src/interfaces/searchInterfaces.ts, src/services/projectServices.ts
- added pagination for when forced to frame projects are fetched for reports to see if it would make the api not crash cause of too large responses
=> test pagination for loading forced to frame projects

src/components/Report/DownloadPdfButton.tsx, src/hooks/useCsvData.ts
After merging main to dev, the merge added extra case labels. This PR removes these.
=> fix: remove duplicate case labels after merge from main

src/components/Project/ProjectBasics/ProjectForm/ProjectFinancialSection.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectFormBanner.tsx, src/components/shared/OverrunRightField.tsx
Project manager is not allowed to delete projects. 
Also fixed permission to fields budgetOverRun (forbidden), projectQualityLevel (allowed), planningPhase (allowed) and constructionPhase (allowed).
Ticket: https://futurice.atlassian.net/jira/software/c/projects/HKISD/boards/62?selectedIssue=HKISD-270
Related PR in backend: https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/245
Set the roles in backend: in file BaseViewSet.py modify the permission_classes so that it includes only the projectManager role. In frontend: in file AuthSlice.ts uncomment from the ad_groups the projectManager group. This will simulate the case when user has only projectManager role.
=> HKSID-270: fix project managers permissions

src/components/Project/ProjectBasics/ProjectForm/ProjectScheduleSection.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectStatusSection.tsx, src/services/projectServices.ts
- removed validation so that date scan be set in the backend instead
=> IO-388: automate setting takuuaika phase to two years

src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectScheduleSection.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectStatusSection.tsx, src/i18n/fi.json
- added the right for project managers to change construction end year forwards
- added automation for changing the year in the date fields when year is modified form planningStartYear or constructionEndYear since it was intended to modify the year from the year fields only, it doesn't make sense that the user should modify it from two separate places.
- tickets: [https://futurice.atlassian.net/browse/HKISD-220](https://futurice.atlassian.net/browse/HKISD-220), [https://futurice.atlassian.net/browse/HKISD-227](https://futurice.atlassian.net/browse/HKISD-227)
=> HKISD-220 & HKISD-227: Project manager right to change construction end year forwards and fix validation errors for dates

src/components/Project/ProjectBasics/ProjectForm/ProjectStatusSection.tsx
- changed project card validation so that estPlanningStart and estConstructionEnd are required if planningStartYear or constructionEndYear is required
- ticket: [https://helsinkisolutionoffice.atlassian.net/browse/IO-446](https://helsinkisolutionoffice.atlassian.net/browse/IO-446)
=> IO-446: require dates when years are required

src/components/Project/ProjectBasics/ProjectForm/ProjectStatusSection.tsx
This fixes bug, where info "Aika on oltava myöhemmin kuin Rakentaminen alkaa", when `planningStartYear` and `constructionEndYear` was set but `estPlanningStart` and `estConstructionEnd` values were empty.
https://futurice.atlassian.net/browse/HKISD-227
=> HKISD-227/fix missing date values info on project card

src/App.test.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectForm.test.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectProgramSection.tsx, src/components/TopBar/TopBar.test.tsx, src/components/shared/TextField.tsx, src/forms/useProjectForm.ts, src/i18n/fi.json, src/interfaces/common.ts, src/interfaces/formInterfaces.ts, src/interfaces/projectInterfaces.ts, src/mocks/mockLists.ts, src/reducers/listsSlice.ts, src/services/listServices.ts, src/utils/mockGetResponseProvider.ts
- added two new fields to project card (budgetOverrunReason, otherBudgetOverrunReason)
- added validation so that other reason field can't be null if "other reason" is selected from the budgetOverrunReasons
- ticket: [https://helsinkisolutionoffice.atlassian.net/browse/IO-426](https://helsinkisolutionoffice.atlassian.net/browse/IO-426)
- API PR: [https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/294](https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/294)
=> IO-426: budget overrun reason to project card

src/components/Report/PdfReports/ReportContainer.tsx, src/components/Report/PdfReports/ReportTable.tsx, src/components/Report/PdfReports/TableRow.tsx, src/components/Report/PdfReports/reportHeaders/StrategyAndForecastTableHeader.tsx, src/i18n/fi.json, src/utils/reportHelpers.ts
- add kilo euros on header row and refactor texts
- show project phase on Forecast report instead of "r" and "s"
- show coordinator timeline on Forecast report instead of forcedToFrame dates
extra:
- fix: set correct width for split planning and customer cells
- refactor: change file and function names
https://helsinkisolutionoffice.atlassian.net/browse/IO-449
=> IO-449/forecast report minor changes

src/components/Project/ProjectHeader/ProjectHeader.tsx
When a new project is created, it shows string that is not translated because missing variable
This hides both icon and the phase string when phase is not selected.
=> fix: show default phase correctly when creating a new project

src/components/Report/DownloadCsvButton.tsx, src/components/Report/DownloadPdfButton.tsx, src/components/Report/PdfReports/ReportContainer.tsx, src/components/Report/PdfReports/ReportTable.tsx, src/components/Report/PdfReports/reportHeaders/StrategyAndForecastTableHeader.tsx, src/components/Report/ReportRow.tsx, src/components/Report/ReportYearSelect/ReportYearSelect.tsx, src/components/Report/common.tsx, src/components/Report/styles.css, src/hooks/useCsvData.ts, src/i18n/fi.json, src/interfaces/reportInterfaces.ts, src/mocks/mockResizeObserver.ts, src/setupTests.ts, src/utils/reportHelpers.ts, src/views/ReportsView/ReportsView.tsx
User can select year from a dropdown for strategy report ranging from previous year to ten years ahead.
ticket: https://helsinkisolutionoffice.atlassian.net/browse/IO-390
=> IO-390 make it possible to select year for strategy report

src/components/Planning/PlanningTable/PlanningRow/PlanningRow.tsx, src/hooks/usePlanningRows.ts
Fixed an issue where if project was displayed directly under a district (suurpiiri) its budget for each year would not be shown in the sums of district header row.
- ticket: https://helsinkisolutionoffice.atlassian.net/browse/IO-733
=> fix: IO-733 wrong sums in programming view

src/hooks/usePlanningRows.ts
Fix problem where frame budget sums entered in coordination view would not be displayed for subclasses that are not 'suurpiiri' in planning view.
https://helsinkisolutionoffice.atlassian.net/browse/IO-746
=> fix: IO-746 Frame budget sums not displayed for some subclasses in planning view

src/utils/reportHelpers.ts
Under million summary rows were removed from construction program reports due to misunderstanding so put them back with a fix that was originally intended that they are not shown under "8 10 Suuret liikennehankkeet".
https://helsinkisolutionoffice.atlassian.net/browse/IO-456
=> fix: IO-456 Put under million summary rows back to construction program reports with a fix

src/components/Project/ProjectBasics/ProjectForm/ProjectFinancialSection.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectForm.test.tsx, src/components/Project/ProjectBasics/ProjectForm/ProjectForm.tsx, src/components/shared/TextAreaField.tsx, src/forms/useProjectForm.ts, src/i18n/fi.json, src/interfaces/formInterfaces.ts, src/interfaces/projectInterfaces.ts, src/mocks/mockLists.ts, src/utils/reportHelpers.ts
* Add onSchedule selection group displayed when budget overrun reason is 'otherReason'
* Disable 'otherBudgetOverrunReason' textbox when overrun reason is not 'otherReason'
Ticket: https://helsinkisolutionoffice.atlassian.net/browse/IO-739
API PR: https://github.com/City-of-Helsinki/infraohjelmointi-api/pull/328
=> IO-739 Changes to budget overrun reason in project form

src/utils/reportHelpers.test.ts, src/utils/reportHelpers.ts
Fix problem where frame budget sums in Forecast report TA column were retrieved from the next year instead of current year.
https://helsinkisolutionoffice.atlassian.net/browse/IO-754
=> fix: IO-754 Forecast report frame budget sums retrieved from wrong year

src/mocks/createMocks.ts, src/utils/reportHelpers.test.ts, src/utils/reportHelpers.ts
In Construction program forecast report, do not count SAP costs multiple times from projects with the same `sapProject` under a same group.
=> fix: IO-757 Construction program forecast report SAP costs fix
